alter table orders no force row level security;
alter table order_items no force row level security;
drop trigger if exists trg_order_items_tax_snapshot_immutable on order_items;
drop function if exists panelya_protect_order_item_tax_snapshot();
drop trigger if exists trg_orders_invoice_snapshot_immutable on orders;
drop function if exists panelya_protect_invoice_snapshot();
drop table if exists invoice_documents;
drop table if exists invoices;
alter table order_items drop column if exists tax_snapshot;
alter table order_items drop column if exists discount_allocation;
alter table order_items drop column if exists gross_amount;
alter table order_items drop column if exists tax_amount;
alter table order_items drop column if exists net_amount;
alter table order_items drop column if exists tax_rate;
alter table orders drop column if exists invoice_retention_until;
alter table orders drop column if exists currency;
alter table orders drop column if exists net_total;
alter table orders drop column if exists tax_snapshot;
alter table orders drop column if exists invoice_snapshot;
alter table orders drop column if exists invoice_profile_id;
drop table if exists product_tax_settings;
drop table if exists customer_invoice_profiles;
drop table if exists organization_legal_profiles;
alter table orders force row level security;
alter table order_items force row level security;
